
[font]
size = 10.0

[env]
TERM = "xterm-256color"

[general]
import = [
    "/home/udragg/.config/alacritty/themes/catppuccin-macchiato.toml"
    # "/home/udragg/.config/alacritty/themes/ayu_dark.toml"
]

# [shell]
# program = "/usr/bin/tmux"
# args = ["new", "-t", "main"]
