theme = "catppuccin_macchiato"

[editor]
true-color = true
line-number = "relative"
mouse = true
clipboard-provider = "tmux"
completion-timeout = 5
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.lsp]
display-progress-messages = true

[editor.file-picker]
hidden = false

[editor.smart-tab]
enable = false

[keys.normal]
"A-j" = ["scroll_down", "move_visual_line_down"]
"A-k" = ["scroll_up", "move_visual_line_up"]
"A-h" = "goto_previous_buffer"
"A-l" = "goto_next_buffer"
"C-e" = "scroll_down"
"C-y" = "scroll_up"
