[[language]]
name = "rust"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[[language]]
name = "python"
language-servers = [ "basedpyright" ]

[[language]]
name = "nix"
formatter = { command = "alejandra" }
